name: Fetch Clone Data

# on:
#   schedule:
#     - cron: '0 0 * * *' # Run every day at midnight UTC

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Traffic to Badge
      uses: yi-Xu-0100/traffic-to-badge@v1.4.0
            