# on:
#   schedule:
#     - cron: '0 0 * * *' # Run every day at midnight UTC

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch clone data
      run: |
        python - << EOF
        import requests, re
        from datetime import datetime, timedelta

        def get_clone_counts(repo_owner, repo_name, since_date):
            url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/traffic/clones"
            params = {'per': 'day', 'since': since_date}
            response = requests.get(url, params=params)
            if response.status_code == 200:
                return response.json()
            else:
                print(f"Failed to fetch clone data. Status code: {response.status_code}")
                return None

        def calculate_accumulative_sum(clone_data):
            accumulative_sum = 0
            for day_data in clone_data['clones']:
                accumulative_sum += day_data['count']
            return accumulative_sum

        repo_owner = "sinamoghimi73"
        repo_name = "GazeGenesis"
        since_date = (datetime.utcnow() - timedelta(days=3650)).isoformat()  # Change the number of days as needed
        clone_data = get_clone_counts(repo_owner, repo_name, since_date)
        if clone_data:
            accumulative_sum = calculate_accumulative_sum(clone_data)
            print(f"Accumulative sum of clones: {accumulative_sum}")
            # badge_url = f"https://img.shields.io/badge/Clones-{accumulative_sum}-blue"

            pattern = r'\[!\[Clones\]\(https://img.shields.io/badge/Clones-\d+-blue\)\]\(https://github\.com/sinamoghimi73/GazeGenesis\)'
            with open("README.md", "r") as f:
                readme_content = f.read()
            readme_content = re.sub(pattern, f'[![Clones](https://img.shields.io/badge/Clones-{accumulative_sum}-blue)](https://github.com/sinamoghimi73/GazeGenesis)', readme_content)
            with open("README.md", "w") as f:
                f.write(readme_content)
        EOF