name: Fetch Clone Data

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Fetch clone data
      run: python .scripts/fetch_clone_data.py
      
    - name: Save accumulative clone count to file
      run: echo "::set-output name=accumulative_clone_count::$(cat accumulative_clone_count.txt)"
      
    - name: Generate badge URL
      id: badge_url
      run: echo "::set-output name=badge_url::https://img.shields.io/badge/Clones-$(echo ${{ steps.update_readme.outputs.accumulative_clone_count }})-blue"
      
    - name: Save badge URL to file
      run: echo "${{ steps.badge_url.outputs.badge_url }}" > badge_url.txt

    - name: Update README with badge
      run: |
            sed -i "s|badge_placeholder|$(cat badge_url.txt)|" README.md
